### ISSUE TITLE
packageClasses endpoint needs being documented

### ISSUE THREAD

**Issue by melkyades** [guillermoamaral/Webside#131]
an entry describing `packageClasses` is missing in the description of the api [here](https://github.com/guillermoamaral/Webside/tree/main/docs/api). I just noticed that Webside is targeting that endpoint but no description is provided

**Comment by guillermoamaral** [comment]
I see it at https://github.com/guillermoamaral/Webside/tree/main/docs/api, under [Code section](https://github.com/guillermoamaral/Webside/tree/main/docs/api).

![image](https://github.com/user-attachments/assets/d6882911-4861-49d9-9003-4d780f4799ec)

In [Code endpoints page](https://github.com/guillermoamaral/Webside/tree/main/docs/api/code) and in the target [endpoint page](https://github.com/guillermoamaral/Webside/blob/main/docs/api/code/packages/name/classes/get.md)

**Comment by melkyades** [comment]
What is missing is `packageClasses`, not to be confused with `package/{name}/classes`. If it's the same, at least it should be indicated (or removed?)

**Comment by guillermoamaral** [comment]
Where do you "see" packageClasses is missing?

**Comment by melkyades** [comment]
That endpoint is being requested by webside in practice, to my egg server
