### ISSUE TITLE
Unable to access a pharo image via the idea.webside.app interface

### ISSUE THREAD

**Issue by andyburnett** [guillermoamaral/Webside#154]
**Describe the bug**
I have a pharo image running on a local server. The image responds when I access e.g. http://127.0.0.1:9002/pharo and the various teapot routes all seem to respond correctly. 

**To Reproduce**
1. Open idea.webside.app
2. Set Target Smalltalk URL to http://127.0.0.1:9002/pharo
3. Set Developer to AB
4. Click on Connect
5. Error message "Cannot connect to http://127.0.0.1:9002/pharo

**Expected behavior**
I was hoping to see the browser

**Desktop (please complete the following information):**
 - MacOS: 12.7.6
 - Browser Safari
 - Version 17.6

**Additional context**

**Comment by guillermoamaral** [comment]
Hi Andy!

That should be probably because the server hosting ide.webside.app (render) cannot access to your localhost (127.0.0.1).
You are using MacOS so you cannot dowload the Electron version of Webside (by the moment; I will try to generate an executable for MacOS).
I suggest you to either clone the repo and run the frontend (IDE) locally, or try (I did not try it with Pharo/Webside server) something to expose your host to Internet (ngrok for instance). But I would go for the former.

Let me know if you need more help.

Regards,

**Comment by andyburnett** [comment]
Thanks, I can definitely try building a local version. However, I am still pondering the problem. My server is accessible via Tailscale. I have just managed to access the /pharo end point via safari on my phone. So that is definitely working. However, loading the webside.app site won’t let me make the connection. 

Perhaps I am Misunderstanding how webside works. I assumed the code ran in my browser, but does it actually proxy through another server - in which case this wouldn’t work. 

I have to say that I am very excited about webside because it seems as though I could finally run smalltalk from my iPad :-)

**Comment by andyburnett** [comment]
Actually, I followed your advice and built a local copy of the client. Everything is now working! It’s great.However, I did notice a few errors in the documentation. Is it useful for me to submit patches? Or are you already aware of that it’s just a matter of tidying them up?On Nov 22, 2024, at 13:47, Guille Amaral ***@***.***> wrote:﻿
I just tested in my Windows machine and it works.
image.png (view on web)
Can you inspect the page, check why the initial request (I guess it is to /dialect) fails and share that?

**Comment by guillermoamaral** [comment]
Andy,

Any issue report (be it in the documentation or in the functionality) or feature request are wellcome as they contribute to improving Webside.

Keep in mind though that one of the main goals of Webside is to provide common tools/features to every dialect. I mention this as it will not emulate/have every option you may find in Pharo (nor any other dialect). However, it does provide ways of extending the API and thus the IDE (check for instance [Change extensions](https://github.com/guillermoamaral/Webside/blob/main/docs/api/extensions/changes.md)). In fact, I took the work to implement many of the refactorings you have in Pharo, in its specific implementations of the API (i.e., they are not available in say, Dolphin).

Regards,

PS: I though a minute about your original request and I guess I understand now what you were trying to do: launch a web server in Pharo in your Mac computer, then trying to connect from you Ipad using a local IP address.
