### ISSUE TITLE
The download link on the website points to a google drive file that google is blocking by policy

### ISSUE THREAD

**Issue by andyburnett** [guillermoamaral/Webside#155]
**Describe the bug**
Clicking on the download link results in a Google error message

**To Reproduce**
1. Go to the bottom of the https://webside.app page
2. Click on 'Download button
3. Google drive throws an error
4. See error: We're sorry. You can't access this item because it is in violation of our [Terms of Service](http://www.google.com/google-d-s/intl/en/terms.html).

**Desktop (please complete the following information):**
 - OS: MacOS 15.1.1
 - Browser Safari
 - Version 18.1.1

**Comment by guillermoamaral** [comment]
Fixed. It points to the latest release now.
