### ISSUE TITLE
Too much whitespace in the changes browser when items overflow columns

### ISSUE THREAD

**Issue by jpimas** [guillermoamaral/Webside#62]
The changeset browser window is already quite small, making rows double size on overflow leaves too little items on view:

compare this:
![image](https://github.com/guillermoamaral/Webside/assets/56401390/6a5b94e7-30cf-4e8d-8782-165959948f63)

to this:
![image](https://github.com/guillermoamaral/Webside/assets/56401390/b21d6ff5-0db9-4b8b-b430-f32703c32077)

**Comment by guillermoamaral** [comment]
This should be solved after making tools occupy the full width of the container.
