### ISSUE TITLE
Changing the superclass of a class is not reflected in the class tree

### ISSUE THREAD

**Issue by jpimas** [guillermoamaral/Webside#68]
To reproduce:
1. Create classes Parent1 and Parent2.
2. Create A as sublclass of Parent1.
3. Go back to class Parent1 in class browser.
4. Select subitem A in class browser
5. Change A definition to be a subclass of Parent2.

The treeview still shows A as a subclass of Parent1. If you inspect A you will see that the change was applied, just the treeview wasn't updated.

**Comment by guillermoamaral** [comment]
Fixed with new SystemBrowser.
