### ISSUE TITLE
Sendes button is covered by scrollbar

### ISSUE THREAD

**Issue by ceferro** [guillermoamaral/Webside#70]
When using the class browser, the pane for the methods shows small buttons to the right for implementors, senders or run test.
But if there is a vertical scrollbar in that pane, the senders button is not visible:

![image](https://github.com/guillermoamaral/Webside/assets/25391265/50262532-5bc5-4c7c-b36f-5d01a0ee5c92)

**Comment by guillermoamaral** [comment]
This happened only in Firefox. I fixed by adding an extra right margin.
