### ISSUE TITLE
Package browser selection after search

### ISSUE THREAD

**Issue by ceferro** [guillermoamaral/Webside#71]
(using Bee)
1. Shift + Enter to search
2. Search Depreciation
3. Go down in the list to packages section
4. Double click on Depreciation Tests
5. A package browser opens, it has Depreciation tests package selected BUT it is not visible, because it is two pages down on the packages list.

**Comment by guillermoamaral** [comment]
Fixed. Since some time ago, whenever a quick search ends up in a package selection, a new SystemBrowser is opened, with the package list filtered using the selected package, and therefore it is shown trivially (and selected).
