### ISSUE TITLE
Class names in class browser should be sorted alphabetically

### ISSUE THREAD

**Issue by melkyades** [guillermoamaral/Webside#83]
Webside connected to egg is showing classes without sorting them:

![image](https://github.com/guillermoamaral/Webside/assets/315241/5d311a3d-5c3d-4e02-a821-01dc92c9993b)

**Comment by guillermoamaral** [comment]
![image](https://github.com/guillermoamaral/Webside/assets/43265642/2eb4934d-77c7-45ab-a2bc-e26c3c11f3b5)
